/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stacks.queues.java;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }


//    @Test
//    public void removeItemFromEmptyQueue(){
//        MyQueue queue = new MyQueue();
//        assertEquals("null result when removing item from empty queue", null, queue.remove());
//    }

}
